#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Single entry point for Azure DevOps governance-as-code.

.DESCRIPTION
    Bootstraps dependencies, imports the in-repo AdoGovernance module, and
    dispatches a command across one or all programs under programs/.

    Each program is a folder programs/<name>/ containing:
      hierarchy.yaml   the authored org hierarchy
      access.yaml      roles + group catalog
      members/         membership per short code
      resolved.yaml    (generated by build)

    Commands:
      build     Compile hierarchy -> programs/<name>/resolved.yaml (+ validate)
      validate  Schema + rules + Azure DevOps limits, no live calls
      plan      Diff resolved vs live Azure DevOps -> change set
      apply     Reconcile Azure DevOps to the resolved desired state
      audit     Read-only compliance report

.EXAMPLE
    pwsh ./build.ps1 build                        # build every program
    pwsh ./build.ps1 build    -Program odyssey # build one program
    pwsh ./build.ps1 validate
    pwsh ./build.ps1 plan  -Program odyssey -Org example-org
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('build', 'validate', 'plan', 'apply', 'audit')]
    [string]$Command = 'build',

    [string]$Program,
    [string]$Org
)

$ErrorActionPreference = 'Stop'

$moduleManifest = Join-Path $PSScriptRoot 'module/AdoGovernance/AdoGovernance.psd1'
$programsRoot   = Join-Path $PSScriptRoot 'programs'
$buildRoot      = Join-Path $PSScriptRoot 'out'

# 1. self-install external dependencies (once)
foreach ($dep in 'powershell-yaml') {
    if (-not (Get-Module -ListAvailable -Name $dep)) {
        Write-Host "Installing dependency '$dep'..." -ForegroundColor Cyan
        Install-Module $dep -Scope CurrentUser -Force -AcceptLicense -Repository PSGallery
    }
}

# 2. reference the in-repo module (imports its RequiredModules automatically)
Import-Module $moduleManifest -Force

# 3. resolve target program(s)
$programPaths = if ($Program) {
    $path = Join-Path $programsRoot $Program
    if (-not (Test-Path $path)) { throw "Program not found: $path" }
    @($path)
}
else {
    @(Get-ChildItem -Path $programsRoot -Directory | Select-Object -ExpandProperty FullName)
}
if ($programPaths.Count -eq 0) { throw "No programs found under $programsRoot" }

# 4. dispatch per program. resolved.yaml is a build artifact under out/ (gitignored).
foreach ($programPath in $programPaths) {
    $name         = Split-Path $programPath -Leaf
    $resolvedPath = Join-Path $buildRoot (Join-Path $name 'resolved.yaml')

    switch ($Command) {
        'build'    { Invoke-GovernanceBuild -ProgramPath $programPath -OutputPath $resolvedPath }
        'validate' { Test-Governance        -ProgramPath $programPath }
        'plan'     { Invoke-GovernancePlan   -ResolvedPath $resolvedPath -Org $Org }
        'apply'    { Invoke-GovernanceApply  -ResolvedPath $resolvedPath -Org $Org }
        'audit'    { Invoke-GovernanceAudit  -ResolvedPath $resolvedPath -Org $Org }
    }
}
